# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simplemap-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for simplemap-ios
  pod 'SDWebImage', '~>3.8'
  pod 'SDWebImage/MapKit'
  pod "Yoga", :path => “./node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => ‘./node_modules/react-native'
end
